In [1]:
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.DataFrame(
    np.random.rand(100,2)/[50,50] + [35.69, 139.70],
    columns = ["lat", "lon"]    
)
df

          lat         lon
0   35.692025  139.711399
1   35.702454  139.705187
2   35.696293  139.717822
3   35.709379  139.703438
4   35.696113  139.713645
..        ...         ...
95  35.692159  139.705280
96  35.690559  139.711337
97  35.707758  139.703606
98  35.692287  139.716217
99  35.692548  139.705942

[100 rows x 2 columns]